====================================================================================
						ESTADO DE FUERZA NUEVO SCRIPT 
====================================================================================
ETFU_DP

GRANT SELECT ON CIBER_DETALLE_EVALUACIONES TO "482000";
GRANT SELECT ON CIBER_EVALUACIONES TO "482000";
GRANT SELECT ON CIBER_PREGUNTAS TO "482000";
GRANT SELECT ON CIBER_RESPUESTAS TO "482000";
GRANT SELECT ON CIBER_SUBTEMAS TO "482000";
GRANT SELECT ON CIBER_TEMAS TO "482000";
GRANT SELECT ON CIBER_USUARIOS TO "482000";
GRANT SELECT ON GRADOS TO "482000";
GRANT SELECT ON MDEP TO "482000";
GRANT SELECT ON MORG TO "482000";
GRANT SELECT ON MPER TO "482000";

GRANT SELECT,INSERT,UPDATE ON est_dest_det TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_destinos TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza_alum_y_rsrv TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza_detalle TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_reg_dep TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_regiones TO "482000";


====================================================================================
ETFU_C

GRANT SELECT ON CIBER_DETALLE_EVALUACIONES TO "482000";
GRANT SELECT ON CIBER_EVALUACIONES TO "482000";
GRANT SELECT ON CIBER_PREGUNTAS TO "482000";
GRANT SELECT ON CIBER_RESPUESTAS TO "482000";
GRANT SELECT ON CIBER_SISTEMAS TO "482000";
GRANT SELECT ON CIBER_TEMAS TO "482000";
GRANT SELECT ON CIBER_USUARIOS TO "482000";
GRANT SELECT ON GRADOS TO "482000";
GRANT SELECT ON MDEP TO "482000";
GRANT SELECT ON MORG TO "482000";
GRANT SELECT ON MPER TO "482000";

GRANT SELECT,INSERT,UPDATE ON est_dest_det TO "482000";
GRANT SELECT ON est_destinos TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza_alumn_y_rsrv TO "482000";
GRANT SELECT,INSERT,UPDATE ON est_fuerza_detalle TO "482000";
GRANT SELECT ON est_reg-deo TO "482000";
GRANT SELECT ON est_regiones TO "482000";
====================================================================================
====================================================================================
