select 
(
   CASE
      WHEN gra_clase = 1 THEN  "Oficiales de Carrera"
      WHEN gra_clase = 2 THEN  "Oficiales de Reservas"
      WHEN gra_clase = 3 THEN  "Oficiales Asimilados"
      WHEN gra_clase = 4 THEN  "Especialistas "
      WHEN gra_clase = 5 THEN  "Cadetes"
      WHEN gra_clase = 6 THEN  "Tropa"
   END
          ), gra_codigo,
(CASE
	WHEN gra_codigo = 0 THEN	"SIN GRADO                     "
	WHEN gra_codigo = 1 THEN	"SIN GRADO                     "
	WHEN gra_codigo = 2 THEN	"SOLDADO SEGUNDA TROPA ESP.    "
	WHEN gra_codigo = 3 THEN	"SOLDADO DE SEGUNDA            "
	WHEN gra_codigo = 4 THEN	"SOLDADO DE SEGUNDA            "
	WHEN gra_codigo = 5 THEN	"MARINERO DE TERCERA           "
	WHEN gra_codigo = 6 THEN	"SOLDADO SEGUNDA ESPECIALISTA  "
	WHEN gra_codigo = 7 THEN	"INFANTE                       "
	WHEN gra_codigo = 8 THEN	"SOLDADO DE PRIMERA            "
	WHEN gra_codigo = 9 THEN	"SLODADO DE PRIMERA TROPA ESP. "
	WHEN gra_codigo = 10 THEN	"MARINERO DE SEGUNDA           "
	WHEN gra_codigo = 11 THEN	"SOLDADO PRIMERA ESPECIALISTA  "
	WHEN gra_codigo = 12 THEN	"POLICIA MILITAR               "
	WHEN gra_codigo = 13 THEN	"CABALLERO ALUMNO              "
	WHEN gra_codigo = 14 THEN	"CABALLERO CADETE              "
	WHEN gra_codigo = 15 THEN	"DAMA CADETE                   "
	WHEN gra_codigo = 16 THEN	"CABO                          "
	WHEN gra_codigo = 17 THEN	"CABO TROPA ESPECIALIZADA      "
	WHEN gra_codigo = 18 THEN	"MARINERO DE PRIMERA           "
	WHEN gra_codigo = 19 THEN	"CABO ESPECIALISTA             "
	WHEN gra_codigo = 20 THEN	"INFANTE DE PRIMERA            "
	WHEN gra_codigo = 21 THEN	"SARGENTO SEGUNDO              "
	WHEN gra_codigo = 22 THEN	"SARGENTO SEGUNDO TROPA ESP.   "
	WHEN gra_codigo = 23 THEN	"CONTRA MAESTRE                "
	WHEN gra_codigo = 24 THEN	"SARGENTO SEGUNDO ESPECIALISTA "
	WHEN gra_codigo = 26 THEN	"SARGENTO PRIMERO              "
	WHEN gra_codigo = 27 THEN	"TROPA ESPECIALIZADA           "
	WHEN gra_codigo = 28 THEN	"SARGENTO PRIMERO ESPECIALISTA "
	WHEN gra_codigo = 29 THEN	"MAESTRE                       "
	WHEN gra_codigo = 30 THEN	"MAESTRE TECNICO               "
	WHEN gra_codigo = 31 THEN	"SARGENTO TECNICO ESPECIALISTA "
	WHEN gra_codigo = 32 THEN	"MAESTRE MAYOR                 "
	WHEN gra_codigo = 33 THEN	"SARGENTO MAYOR ESPECIALISTA   "
	WHEN gra_codigo = 34 THEN	"SARGENTO COMANDANTE PELOTON   "
	WHEN gra_codigo = 35 THEN	"ESPECIALISTA SIN GRADO        "
	WHEN gra_codigo = 36 THEN	"ALFEREZ FRAGATA ASIMILADO     "
	WHEN gra_codigo = 37 THEN	"SUBTENIENTE ASIMILADO         "
	WHEN gra_codigo = 38 THEN	"ALFEREZ FRAGATA RETIRADO      "
	WHEN gra_codigo = 39 THEN	"SUBTENIENTE DE RESERVAS       "
	WHEN gra_codigo = 40 THEN	"ALFEREZ DE FRAGATA            "
	WHEN gra_codigo = 41 THEN	"SUBTENIENTE                   "
	WHEN gra_codigo = 42 THEN	"ALFEREZ NAVIO ASIMILADO       "
	WHEN gra_codigo = 43 THEN	"TENIENTE ASIMILADO            "
	WHEN gra_codigo = 44 THEN	"ALFEREZ NAVIO DE RESERVAS     "
	WHEN gra_codigo = 45 THEN	"TENIENTE DE RESERVAS          "
	WHEN gra_codigo = 46 THEN	"ALFEREZ DE NAVIO              "
	WHEN gra_codigo = 47 THEN	"TENIENTE                      "
	WHEN gra_codigo = 50 THEN	"CAPITAN ASIMILADO             "
	WHEN gra_codigo = 51 THEN	"CAPITAN DE RESERVAS           "
	WHEN gra_codigo = 52 THEN	"CAPITAN                       "
	WHEN gra_codigo = 54 THEN	"TENIENTE DE FRAGATA ASIMILADO "
	WHEN gra_codigo = 55 THEN	"CAPITAN SEGUNDO ASIMILADO     "
	WHEN gra_codigo = 57 THEN	"TENIENTE DE FRAGATA DE RESERVA"
	WHEN gra_codigo = 58 THEN	"CAPITAN SEGUNDO DE RESERVAS   "
	WHEN gra_codigo = 59 THEN	"TENIENTE DE FRAGATA           "
	WHEN gra_codigo = 60 THEN	"CAPITAN SEGUNDO               "
	WHEN gra_codigo = 61 THEN	"TENIENTE DE NAVIO ASIMILADO   "
	WHEN gra_codigo = 62 THEN	"CAPITAN PRIMERO ASIMILADO     "
	WHEN gra_codigo = 63 THEN	"TENIENTE DE NAVIO DE RESERVAS "
	WHEN gra_codigo = 64 THEN	"CAPITAN PRIMERO DE RESERVAS   "
	WHEN gra_codigo = 65 THEN	"TENIENTE DE NAVIO             "
	WHEN gra_codigo = 66 THEN	"CAPITAN PRIMERO               "
	WHEN gra_codigo = 69 THEN	"CAPITAN DE CORBETA ASIMILADO  "
	WHEN gra_codigo = 70 THEN	"MAYOR ASIMILADO               "
	WHEN gra_codigo = 71 THEN	"CAPITAN DE CORBETA DE RESERVAS"
	WHEN gra_codigo = 72 THEN	"MAYOR DE RESERVAS             "
	WHEN gra_codigo = 73 THEN	"CAPITAN DE CORBETA            "
	WHEN gra_codigo = 74 THEN	"MAYOR                         "
	WHEN gra_codigo = 77 THEN	"CAPITAN DE FRAGATA ASIMILADO  "
	WHEN gra_codigo = 78 THEN	"TENIENTE CORONEL ASIMILADO    "
	WHEN gra_codigo = 79 THEN	"CAPITAN DE FRAGATA DE RESERVAS"
	WHEN gra_codigo = 80 THEN	"TENIENTE CORONEL DE RESERVAS  "
	WHEN gra_codigo = 81 THEN	"CAPITAN DE FRAGATA            "
	WHEN gra_codigo = 82 THEN	"TENIENTE CORONEL              "
	WHEN gra_codigo = 85 THEN	"CAPITAN DE NAVIO ASIMILADO    "
	WHEN gra_codigo = 86 THEN	"CORONEL ASIMILADO             "
	WHEN gra_codigo = 87 THEN	"OFICIAL ASIMILADO SIN GRADO   "
	WHEN gra_codigo = 88 THEN	"CAPITAN DE NAVIO              "
	WHEN gra_codigo = 89 THEN	"CORONEL                       "
	WHEN gra_codigo = 92 THEN	"VICE-ALMIRANTE                "
	WHEN gra_codigo = 93 THEN	"GENERAL DE BRIGADA            "
	WHEN gra_codigo = 96 THEN	"ALMIRANTE                     "
	WHEN gra_codigo = 97 THEN	"GENERAL DE DIVISION           "
	WHEN gra_codigo = 99 THEN	"OFICIAL SIN GRADO             "
END
), COUNT(gra_codigo)
from jefes,mper,grados,armas,mdep,morg
where per_arma =arm_codigo
and   per_grado =gra_codigo
and   per_plaza=org_plaza
and   org_dependencia=dep_llave
and   per_plaza =jef_plaza
and   jef_categoria in("0100", "0101","0102","0103","0104")

GROUP BY 1,2