INSERT INTO sica_grado_curso VALUES (81, 'CURSO BASICO DE ARMAS Y SERVICIOS', 'CURSO BASICO',2, 10);
INSERT INTO sica_grado_curso VALUES (82, 'CURSO AVANZADO DE ARMAS', 'AVANZ. ARMAS',2, 10);
INSERT INTO sica_grado_curso VALUES (83, 'ALTOS ESTUDIOS ESTRATEGICOS', 'ALT EST. ESTRAT.',2, 10);
INSERT INTO sica_grado_curso VALUES (84, 'DIPLOMADO EN ESTADO MAYOR', 'CURSO DEM',2, 10);
INSERT INTO sica_grado_curso VALUES (85, 'CURSO BASICO DE IDIOMA INGLES', 'CURSO INGLES',2, 10);
INSERT INTO sica_grado_curso VALUES (86, 'CURSO BASICO DE IDIOMA FRANCES', 'CURSO FRANCES',2, 10);
